import * as React from 'react';
import { ArrowRight, ArrowUpRight, CircleHelp, Wallet, Check } from 'lucide-react';
import type { Reconciliation } from '@/lib/types';
import { money } from '@/lib/format';
import { Button } from './ui/button';

export function Revenue({ data, openDoc }: { data: Reconciliation; openDoc: (id: string) => void }) {
  return <><div className="page-heading"><div><div className="eyebrow">REVENUE RECONCILIATION</div><h1>Every dollar, accounted for.</h1><p>{data.period} · Expected fees compared with actual payouts.</p></div></div><div className="revenue-kpis">{[{ label: 'Expected revenue', value: data.expected, note: 'From your practice fee schedule', icon: Wallet }, { label: 'Actual payout', value: data.actual, note: 'From the payout statement', icon: Check }, { label: 'Variance', value: data.variance, note: data.flags.length ? 'Requires follow-up' : 'Fully reconciled', icon: CircleHelp }].map(item => <section className="kpi" key={item.label}><div className="kpi-label">{item.label}<item.icon size={16} /></div><div className="kpi-value">{money(item.value)}</div><div className="kpi-note">{item.note}</div></section>)}</div>
    {data.flags.map(flag => { const line = data.lines.find(l => l.id === flag.lineId); return <div key={flag.lineId} className={`alert ${flag.severity === 'high' ? 'error' : ''}`}><div><strong>{flag.status === 'missing' ? 'Expected payout is missing' : 'Payout needs a closer look'}</strong><p>{flag.message}</p></div>{line?.docId ? <Button variant="outline" onClick={() => openDoc(line.docId!)}>View statement <ArrowRight size={15} /></Button> : <span className="muted">No source document</span>}</div>; })}
    <section className="panel"><div className="panel-heading"><h2>Payout breakdown</h2><span className="muted">{data.period}</span></div><div className="table-scroll"><table><thead><tr><th>Revenue source</th><th>Expected</th><th>Actual</th><th>Variance</th><th>Status</th><th>Source</th></tr></thead><tbody>{data.lines.map(line => <tr key={line.id}><td>{line.label}{line.ref && <small className="table-sub">Reference {line.ref}</small>}{line.reason && <small className="rule-hit">{line.reason}</small>}</td><td>{money(line.expected)}</td><td>{money(line.actual)}</td><td className={['short', 'missing'].includes(line.status) ? 'text-red' : line.status === 'ok' ? 'text-green' : ''}>{money(line.variance)}</td><td><span className={`pill ${line.status}`}>{line.status === 'ok' ? 'Matched' : line.status.charAt(0).toUpperCase() + line.status.slice(1)}</span></td><td>{line.docId ? <button className="document-link" onClick={() => openDoc(line.docId!)}>Payout statement <ArrowUpRight size={13} /></button> : <span className="muted">No statement</span>}</td></tr>)}</tbody></table></div>{!data.lines.length && <div className="empty">No revenue lines for this period.</div>}</section></>;
}
