import * as React from 'react';
import { ArrowRight, ArrowUpRight, CircleHelp, Wallet, Check } from 'lucide-react';
import type { Reconciliation } from '@/lib/types';
import { api } from '@/lib/api';
import { money } from '@/lib/format';
import { Button } from './ui/button';

// Months with payout history: Sep 2025 through the demo month, newest first.
const MONTHS = Array.from({ length: 13 }, (_, i) => { const d = new Date(Date.UTC(2026, 8 - i, 1)); return { value: d.toISOString().slice(0, 7), label: d.toLocaleString('en-US', { month: 'long', year: 'numeric', timeZone: 'UTC' }) }; });

export function Revenue({ data: initial, openDoc }: { data: Reconciliation; openDoc: (id: string) => void }) {
  const [period, setPeriod] = React.useState(initial.period); const [data, setData] = React.useState(initial); const [loading, setLoading] = React.useState(false); const [error, setError] = React.useState('');
  React.useEffect(() => { if (period === initial.period) { setData(initial); return; } let active = true; setLoading(true); setError(''); api.reconciliation(period).then(r => { if (active) setData(r as Reconciliation); }).catch(e => { if (active) setError(e instanceof Error ? e.message : 'Could not load that month.'); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [period, initial]);
  const monthLabel = MONTHS.find(m => m.value === data.period)?.label ?? data.period;
  return <><div className="page-heading"><div><div className="eyebrow">REVENUE RECONCILIATION</div><h1>Every dollar, accounted for.</h1><p>{monthLabel} · Expected fees compared with actual payouts.</p></div><select aria-label="Reconciliation month" value={period} onChange={e => setPeriod(e.target.value)} disabled={loading}>{MONTHS.map(m => <option key={m.value} value={m.value}>{m.label}</option>)}</select></div>{error && <div className="alert error">{error}</div>}<div className="revenue-kpis">{[{ label: 'Expected revenue', value: data.expected, note: 'From your practice fee schedule', icon: Wallet }, { label: 'Actual payout', value: data.actual, note: 'From the payout statement', icon: Check }, { label: 'Variance', value: data.variance, note: data.flags.length ? 'Requires follow-up' : 'Fully reconciled', icon: CircleHelp }].map(item => <section className="kpi" key={item.label}><div className="kpi-label">{item.label}<item.icon size={16} /></div><div className="kpi-value">{money(item.value)}</div><div className="kpi-note">{item.note}</div></section>)}</div>
    {data.flags.map(flag => { const line = data.lines.find(l => l.id === flag.lineId); return <div key={flag.lineId} className={`alert ${flag.severity === 'high' ? 'error' : ''}`}><div><strong>{flag.status === 'missing' ? 'Expected payout is missing' : 'Payout needs a closer look'}</strong><p>{flag.message}</p></div>{line?.docId ? <Button variant="outline" onClick={() => openDoc(line.docId!)}>View statement <ArrowRight size={15} /></Button> : <span className="muted">No source document</span>}</div>; })}
    <section className="panel"><div className="panel-heading"><h2>Payout breakdown</h2><span className="muted">{loading ? 'Loading…' : monthLabel}</span></div><div className="table-scroll"><table><thead><tr><th>Revenue source</th><th>Expected</th><th>Actual</th><th>Variance</th><th>Status</th><th>Source</th></tr></thead><tbody>{data.lines.map(line => <tr key={line.id}><td>{line.label}{line.ref && <small className="table-sub">Reference {line.ref}</small>}{line.reason && <small className="rule-hit">{line.reason}</small>}</td><td>{money(line.expected)}</td><td>{money(line.actual)}</td><td className={['short', 'missing'].includes(line.status) ? 'text-red' : line.status === 'ok' ? 'text-green' : ''}>{money(line.variance)}</td><td><span className={`pill ${line.status}`}>{line.status === 'ok' ? 'Matched' : line.status.charAt(0).toUpperCase() + line.status.slice(1)}</span></td><td>{line.docId ? <button className="document-link" onClick={() => openDoc(line.docId!)}>Payout statement <ArrowUpRight size={13} /></button> : <span className="muted">No statement</span>}</td></tr>)}</tbody></table></div>{!data.lines.length && <div className="empty">No revenue lines for this period.</div>}</section></>;
}
