'use client';

import { useCallback, useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import { usePathname, useRouter } from 'next/navigation';
import { Amplify } from 'aws-amplify';
import { Authenticator } from '@aws-amplify/ui-react';
import '@aws-amplify/ui-react/styles.css';
import { Bar, BarChart, Cell, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { ArrowDownToLine, ArrowRight, ArrowUpRight, Bell, BookOpen, Check, ChevronDown, CircleHelp, CreditCard, FileText, FolderOpen, LayoutDashboard, LoaderCircle, LogOut, Menu, MessageSquare, Plus, Search, Send, ShieldCheck, SlidersHorizontal, Sparkles, UploadCloud, Wallet, X } from 'lucide-react';
import { api, subscribe, USE_MOCKS } from '@/lib/api';
import type { Answer, Bill, Document, Financials, Reconciliation, Role, Rule, Vendor } from '@/lib/types';
import { Button } from '@/components/ui/button';
import { FinancialStatement } from './financial-statements';
import { Revenue } from './revenue-view';
import { percent } from '@/lib/format';

const money = (n: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(n);
const label = (s: string) => s.replaceAll('_', ' ').replace(/\b\w/g, c => c.toUpperCase());
const nav = [{ name: 'Dashboard', path: '/', icon: LayoutDashboard }, { name: 'Inbox', path: '/inbox', icon: UploadCloud }, { name: 'Bills & approvals', path: '/bills', icon: Wallet }, { name: 'Revenue', path: '/revenue', icon: ArrowUpRight }, { name: 'Library', path: '/library', icon: FolderOpen }, { name: 'Ask your books', path: '/ask', icon: MessageSquare }, { name: 'Rules', path: '/rules', icon: SlidersHorizontal }, { name: 'Card transactions', path: '/transactions', icon: CreditCard }];
const authConfigured = Boolean(process.env.NEXT_PUBLIC_COGNITO_USER_POOL_ID && process.env.NEXT_PUBLIC_COGNITO_CLIENT_ID);
if (authConfigured) Amplify.configure({ Auth: { Cognito: { userPoolId: process.env.NEXT_PUBLIC_COGNITO_USER_POOL_ID!, userPoolClientId: process.env.NEXT_PUBLIC_COGNITO_CLIENT_ID! } } });

export function Workspace() {
  if (USE_MOCKS) return <App />;
  if (!authConfigured) return <main className="login"><BookOpen size={36} /><h1>Connect your practice</h1><p>Set the Cognito user pool and client ID in frontend/.env.local to enable secure sign-in.</p></main>;
  return <Authenticator hideSignUp>{({ signOut }) => <App signOut={signOut} />}</Authenticator>;
}

function App({ signOut }: { signOut?: () => void }) {
  const path = usePathname(); const router = useRouter();
  const [role, setRole] = useState<Role>('owner'); const [mobile, setMobile] = useState(false);
  const [documents, setDocuments] = useState<Document[]>([]); const [bills, setBills] = useState<Bill[]>([]); const [vendors, setVendors] = useState<Vendor[]>([]); const [rules, setRules] = useState<Rule[]>([]);
  const [financials, setFinancials] = useState<Financials>(); const [revenue, setRevenue] = useState<Reconciliation>();
  const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [toast, setToast] = useState('');
  const [period, setPeriod] = useState('2026-Q3'); const [busy, setBusy] = useState(''); const [selected, setSelected] = useState<Document>();
  const refresh = useCallback(async () => {
    setError('');
    const results = await Promise.allSettled([api.documents(), api.bills(), api.vendors(), api.rules(), api.financials(period), api.reconciliation('2026-09')]);
    const setters = [setDocuments, setBills, setVendors, setRules, setFinancials, setRevenue];
    results.forEach((result, index) => { if (result.status === 'fulfilled') (setters[index] as (value: unknown) => void)(result.value); else setError(result.reason instanceof Error ? result.reason.message : 'Could not load practice data.'); });
    setLoading(false);
  }, [period]);
  useEffect(() => { void refresh(); return subscribe(() => { void refresh(); }); }, [refresh]);
  useEffect(() => { if (!toast) return; const timer = setTimeout(() => setToast(''), 5000); return () => clearTimeout(timer); }, [toast]);
  useEffect(() => {
    if (!selected) return;
    const previousFocus = document.activeElement as HTMLElement | null;
    const previousOverflow = document.body.style.overflow;
    document.body.style.overflow = 'hidden';
    const onKey = (event: KeyboardEvent) => {
      if (event.key === 'Escape') { setSelected(undefined); return; }
      if (event.key !== 'Tab') return;
      const elements = Array.from(document.querySelectorAll<HTMLElement>('.document-modal button:not(:disabled), .document-modal a[href], .document-modal iframe'));
      const first = elements[0]; const last = elements.at(-1);
      if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last?.focus(); }
      else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first?.focus(); }
    };
    document.addEventListener('keydown', onKey);
    return () => { document.removeEventListener('keydown', onKey); document.body.style.overflow = previousOverflow; previousFocus?.focus(); };
  }, [selected]);
  useEffect(() => { if (USE_MOCKS) return; import('aws-amplify/auth').then(async ({ fetchAuthSession }) => { const groups = (await fetchAuthSession()).tokens?.idToken?.payload['cognito:groups']; if (Array.isArray(groups)) { const actual = groups.find(g => ['owner', 'partner', 'ops', 'lpl_bookkeeper'].includes(String(g))); if (actual) setRole(actual as Role); } }); }, []);
  const openDoc = async (id: string) => { setBusy(id); try { setSelected(await api.document(id)); } catch (e) { setToast(message(e)); } finally { setBusy(''); } };
  const decide = async (bill: Bill, decision: 'approve' | 'reject') => { setBusy(bill.id); try { await api.decision(bill.id, decision, `${label(decision)} by ${role}`, role); setToast(decision === 'approve' ? 'Bill approved. Payment scheduled (mock payment).' : 'Bill rejected.'); await refresh(); } catch (e) { setToast(message(e)); } finally { setBusy(''); } };
  const exportPackage = async () => { setBusy('export'); try { const { downloadUrl, documents: exportedDocs, ledgerLines, missing } = await api.export(period); const a = document.createElement('a'); a.href = downloadUrl; a.download = `ledgerline-${period}.zip`; a.click(); if (downloadUrl.startsWith('blob:')) setTimeout(() => URL.revokeObjectURL(downloadUrl), 10000); setToast(`Export ready: ${exportedDocs} documents, ${ledgerLines} ledger lines.${missing.length ? ` Missing: ${missing.join(', ')}` : ''}`); } catch (e) { setToast(message(e)); } finally { setBusy(''); } };
  const pending = bills.filter(b => b.status === 'pending_approval');
  const title = nav.find(item => item.path === path)?.name ?? 'Document detail';
  return <div className="app-shell">
    <aside className={`sidebar ${mobile ? 'is-open' : ''}`}>
      <Link className="brand" href="/"><span className="brand-icon"><BookOpen size={21} /></span>ledgerline<span className="brand-dot">.</span></Link>
      <div className="practice-switch"><span className="practice-avatar">HP</span><div><strong>Harbor Point Wealth</strong><small>Independent advisor practice</small></div><ChevronDown size={14} /></div>
      <div className="nav-caption">WORKSPACE</div>
      <nav>{nav.map(item => <Link onClick={() => setMobile(false)} className={`nav-item ${path === item.path ? 'active' : ''}`} href={item.path} key={item.path}><item.icon size={18} /><span>{item.name}</span>{item.path === '/bills' && pending.length > 0 && <span className="nav-count">{pending.length}</span>}{item.path === '/ask' && <Sparkles className="nav-spark" size={13} />}</Link>)}</nav>
      <div className="sidebar-bottom"><div className="connected"><span className="status-dot" />{USE_MOCKS ? 'Demo workspace' : 'Connected workspace'}<small>{USE_MOCKS ? 'Fictional data · simulated extraction' : 'Authenticated with Cognito'}</small></div><div className="user"><span className="user-avatar">MC</span><div><strong>Maya Chen</strong><small>{label(role)}</small></div>{signOut && <button aria-label="Sign out" onClick={signOut}><LogOut size={16} /></button>}</div></div>
    </aside>
    <div className="main-area"><header className="topbar"><div className="breadcrumb"><button className="mobile-menu" aria-label="Open navigation" onClick={() => setMobile(!mobile)}><Menu size={20} /></button>Workspace <span>/</span><strong>{title}</strong></div><div className="topbar-right"><span className="demo-tag">{USE_MOCKS ? 'DEMO' : 'LIVE'}</span>{USE_MOCKS ? <select aria-label="Demo role" value={role} onChange={e => { setRole(e.target.value as Role); if (e.target.value === 'partner') router.push('/bills'); }}><option value="owner">Owner view</option><option value="partner">Partner view</option><option value="ops">Operations view</option><option value="lpl_bookkeeper">Bookkeeper view</option></select> : <span>{label(role)}</span>}<button className="icon-button" aria-label="View items needing attention" onClick={() => router.push('/bills')}><Bell size={19} /><i /></button><span className="user-avatar small">MC</span></div></header>
      <main className="content">
        {error && <div role="alert" className="alert error">{error}<Button variant="outline" onClick={() => { setLoading(true); void refresh(); }}>Retry</Button></div>}
        {loading ? <div className="skeleton-grid" aria-label="Loading practice data">{[1, 2, 3, 4, 5, 6].map(n => <div key={n} className="skeleton" />)}</div> : <>
          {path === '/' && financials && <Dashboard data={financials} bills={bills} revenue={revenue} period={period} setPeriod={setPeriod} exportPackage={exportPackage} exporting={busy === 'export'} />}
          {path === '/inbox' && <><PageHeading eyebrow="DOCUMENT INTAKE" title="Less paperwork. More perspective." description="Drop in a document. We'll take it from here." /><Upload onComplete={doc => { setSelected(doc); void refresh(); }} notify={setToast} /><DocumentTable documents={documents} openDoc={openDoc} /></>}
          {path === '/bills' && <><PageHeading eyebrow="PAYABLES" title="Bills & approvals" description="Every payment, with the right checks in place." action={<Link className="button primary" href="/inbox"><Plus size={16} /> Upload a bill</Link>} /><div className="summary-strip"><span><strong>{pending.length}</strong> awaiting approval</span><span><strong>{money(pending.reduce((s, b) => s + b.amount, 0))}</strong> pending total</span><span><ShieldCheck size={16} /> Payments are simulated</span></div><BillsTable bills={bills} role={role} busy={busy} decide={decide} openDoc={openDoc} /></>}
          {path === '/revenue' && revenue && <Revenue data={revenue} openDoc={openDoc} />}
          {path === '/library' && <Library documents={documents} vendors={vendors} openDoc={openDoc} exportPackage={exportPackage} exporting={busy === 'export'} />}
          {path === '/ask' && <Ask openDoc={openDoc} />}
          {path === '/rules' && <Rules rules={rules} notify={setToast} refresh={refresh} />}
          {path === '/transactions' && <Transactions notify={setToast} />}
          {path.startsWith('/documents/') && <DocumentRoute id={decodeURIComponent(path.split('/')[2] ?? '')} />}
          {!nav.some(n => n.path === path) && !path.startsWith('/documents/') && <Empty text="This page does not exist." />}
        </>}
        <footer className="footer"><span><ShieldCheck size={13} /> {USE_MOCKS ? 'Sample workspace · fictional data' : 'Secure practice workspace'}</span><span>Made for the business behind your advice.</span></footer>
      </main>
    </div>
    {toast && <div className="toast" role="status"><CircleHelp size={18} /><span>{toast}</span><button aria-label="Dismiss notification" onClick={() => setToast('')}><X size={16} /></button></div>}
    {selected && <div className="modal-backdrop" onClick={() => setSelected(undefined)}><section className="document-modal" role="dialog" aria-modal="true" aria-label="Document detail" onClick={e => e.stopPropagation()}><div className="modal-title"><strong>Document detail</strong><button autoFocus aria-label="Close document" onClick={() => setSelected(undefined)}><X size={21} /></button></div><DocumentDetail doc={selected} vendors={vendors} /><Button variant="outline" onClick={() => { router.push(`/documents/${selected.id}`); setSelected(undefined); }}>Open full page <ArrowRight size={15} /></Button></section></div>}
  </div>;
}
function message(e: unknown) { return e instanceof Error ? e.message : 'Something went wrong. Please try again.'; }
function PageHeading({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: React.ReactNode }) { return <div className="page-heading"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{description}</p></div>{action}</div>; }
function Empty({ text }: { text: string }) { return <div className="empty"><FolderOpen size={26} /><p>{text}</p></div>; }
function Pill({ status }: { status: string }) { return <span className={`pill ${status}`}><span />{label(status)}</span>; }

function Dashboard({ data, bills, revenue, period, setPeriod, exportPackage, exporting }: { data: Financials; bills: Bill[]; revenue?: Reconciliation; period: string; setPeriod: (p: string) => void; exportPackage: () => void; exporting: boolean }) {
  const [tab, setTab] = useState('Profit & loss');
  const pending = bills.filter(b => ['pending_approval', 'pending_review'].includes(b.status));
  return <><PageHeading eyebrow="YOUR PRACTICE AT A GLANCE" title="A clear view of what's next." description="Good morning, Maya. Here's how Harbor Point is doing." action={<div className="heading-actions"><select aria-label="Financial period" value={period} onChange={e => setPeriod(e.target.value)}>{USE_MOCKS ? <option value="2026-Q3">Q3 2026 · Jul – Sep</option> : <><option value="2026-Q3">Q3 2026 · Jul – Sep</option><option value="2026-Q2">Q2 2026 · Apr – Jun</option></>}</select><Button variant="outline" disabled={exporting} onClick={exportPackage}><ArrowDownToLine size={15} /> Export</Button></div>} />
    <div className="overview-label"><span className="status-dot" />{USE_MOCKS ? 'Sample financial overview' : 'Financial overview'}<span>180 clients <i>·</i> $250M AUM</span></div>
    <div className="kpi-grid"><Kpi label="Total revenue" value={money(data.pnl.totalRevenue)} note="For the selected quarter" icon={<Wallet size={16} />} /><Kpi label="Operating margin" value={percent(data.kpis.margin)} note={`${money(data.pnl.operatingIncome)} operating income`} icon={<ArrowUpRight size={16} />} /><Kpi label="Recurring revenue" value={percent(data.kpis.recurringPct)} note="A foundation for what's next" icon={<ShieldCheck size={16} />} /><div className="kpi valuation"><div className="kpi-label">Est. practice value <span title={data.valuation.method}><CircleHelp size={15} /></span></div><div className="kpi-value">${(data.valuation.mid / 1e6).toFixed(1)}<small>M</small></div><div className="kpi-note">${(data.valuation.low / 1e6).toFixed(1)}M – ${(data.valuation.high / 1e6).toFixed(1)}M estimated range</div><div className="valuation-line" /><small>Built on your recurring revenue</small></div></div>
    <div className="dashboard-middle"><section className="panel chart-panel"><div className="panel-heading"><div><h2>Your financial picture</h2><p>Revenue and expenses, side by side.</p></div><span className="muted">USD</span></div><div className="tabs" role="tablist">{['Profit & loss', 'Balance sheet', 'Cash flow'].map(name => <button role="tab" aria-selected={tab === name} className={tab === name ? 'selected' : ''} key={name} onClick={() => setTab(name)}>{name}</button>)}</div>{tab === 'Profit & loss' ? <><div className="chart-legend"><span><i className="green" /> Revenue</span><span><i className="gray" /> Expenses</span><span className="chart-period">Selected period totals</span></div><div className="chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={[{ name: 'Revenue', amount: data.pnl.totalRevenue }, { name: 'Expenses', amount: data.pnl.totalExpenses }, { name: 'Operating income', amount: data.pnl.operatingIncome }]} margin={{ top: 15, right: 12, left: -12, bottom: 0 }}><defs><linearGradient id="revenueFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#367b66" stopOpacity={.18} /><stop offset="100%" stopColor="#367b66" stopOpacity={0} /></linearGradient></defs><CartesianGrid strokeDasharray="4 4" vertical={false} stroke="#e9ede9" /><XAxis dataKey="name" axisLine={false} tickLine={false} tick={{ fontSize: 12, fill: '#88928c' }} dy={12} /><YAxis axisLine={false} tickLine={false} tickFormatter={v => `$${v / 1000}k`} tick={{ fontSize: 11, fill: '#88928c' }} /><Tooltip formatter={value => money(Number(value))} /><Bar dataKey="amount" name="Amount" radius={[5, 5, 0, 0]} maxBarSize={65}><Cell fill="#387961" /><Cell fill="#a5b0a8" /><Cell fill="#779568" /></Bar></BarChart></ResponsiveContainer></div><div className="chart-bottom"><span>Quarterly operating income <strong>{money(data.pnl.operatingIncome)}</strong></span><Link href="/ask">Explore your numbers <ArrowRight size={14} /></Link></div></> : <FinancialStatement data={data} tab={tab} />}</section>
    <section className="panel attention-panel"><div className="panel-heading"><div><h2>Needs your attention</h2><p>A little action goes a long way.</p></div><span className="count-bubble">{pending.length + (revenue?.flags.length ?? 0)}</span></div>{pending.slice(0, 2).map(bill => <Link className="attention-item" key={bill.id} href="/bills"><span className="attention-icon amber"><FileText size={18} /></span><div><strong>{bill.status === 'pending_review' ? 'Review extracted fields' : 'Bill awaiting approval'}</strong><p>{bill.vendor} <i>·</i> {money(bill.amount)}</p><small>{bill.ruleHits[0]}</small></div><ArrowRight size={15} /></Link>)}{revenue?.flags.map(flag => <Link className="attention-item" href="/revenue" key={flag.lineId}><span className="attention-icon coral"><ArrowUpRight size={18} /></span><div><strong>Revenue variance found</strong><p>{revenue.lines.find(line => line.id === flag.lineId)?.label ?? label(flag.status)}</p><small className={flag.severity === 'high' ? 'text-red' : ''}>{flag.message}</small></div><ArrowRight size={15} /></Link>)}{pending.length === 0 && !revenue?.flags.length && <Empty text="You're all caught up." />}<Link href="/bills" className="panel-bottom-link">View all activity <ArrowRight size={14} /></Link></section></div>
    <div className="dashboard-bottom"><section className="panel recent-panel"><div className="panel-heading"><div><h2>Recent bills</h2><p>The latest in your back office.</p></div><Link href="/bills">View all <ArrowRight size={14} /></Link></div><div className="table-scroll"><table><thead><tr><th>Vendor</th><th>Category</th><th>Amount</th><th>Status</th></tr></thead><tbody>{bills.slice(0, 3).map(b => <tr key={b.id}><td><span className="vendor-cell"><span className="vendor-avatar">{b.vendor.slice(0, 2).toUpperCase()}</span>{b.vendor}</span></td><td className="muted">{b.glAccount.split('·')[1] ?? b.glAccount}</td><td>{money(b.amount)}</td><td><Pill status={b.status} /></td></tr>)}</tbody></table></div></section><section className="insight-card"><span className="insight-icon"><Sparkles size={22} /></span><div className="eyebrow">A LITTLE MORE CLARITY</div><h2>Your books have answers.</h2><p>Understand the story behind your numbers. Just ask.</p><Link href="/ask" className="suggestion">“Why did my margin drop in Q3?” <ArrowUpRight size={15} /></Link><Link href="/ask" className="insight-link">Ask your books <ArrowRight size={15} /></Link></section></div>
  </>;
}
function Kpi({ label: title, value, note, icon }: { label: string; value: string; note: string; icon: React.ReactNode }) { return <section className="kpi"><div className="kpi-label">{title}<span>{icon}</span></div><div className="kpi-value">{value}</div><div className="kpi-note">{note}</div><div className="kpi-context"><span className="status-dot" /> Selected period</div></section>; }

function Upload({ onComplete, notify }: { onComplete: (doc: Document) => void; notify: (text: string) => void }) {
  const input = useRef<HTMLInputElement>(null); const abort = useRef<AbortController | null>(null); const [status, setStatus] = useState(''); const [dragging, setDragging] = useState(false);
  useEffect(() => () => abort.current?.abort(), []);
  const upload = async (file?: File) => { if (!file || status) return; abort.current = new AbortController(); setStatus('Uploading'); try { const doc = await api.upload(file, setStatus, abort.current.signal); onComplete(doc); notify(USE_MOCKS ? 'Demo document created using sample fields. Uploaded file retained for preview.' : 'Document processed successfully.'); } catch (e) { if (!abort.current.signal.aborted) notify(message(e)); } finally { setStatus(''); if (input.current) input.current.value = ''; } };
  return <section className={`dropzone ${dragging ? 'dragging' : ''}`} onDragOver={e => { e.preventDefault(); setDragging(true); }} onDragLeave={() => setDragging(false)} onDrop={e => { e.preventDefault(); setDragging(false); void upload(e.dataTransfer.files[0]); }}><span className="upload-icon">{status ? <LoaderCircle className="spin" size={30} /> : <UploadCloud size={30} />}</span><h2>{status || 'Give your paperwork a place to land.'}</h2><p>Drag and drop an invoice, receipt, payout statement, W-9 or void check.</p><Button onClick={() => input.current?.click()} disabled={Boolean(status)}><Plus size={16} /> Choose a document</Button><input ref={input} type="file" accept="application/pdf,image/png,image/jpeg" hidden onChange={e => void upload(e.target.files?.[0])} /><small>PDF, PNG or JPG · up to 20 MB {USE_MOCKS && '· Demo fields are simulated'}</small></section>;
}
function DocumentTable({ documents, openDoc }: { documents: Document[]; openDoc: (id: string) => void }) { return <section className="panel"><div className="panel-heading"><h2>Documents <span className="muted">({documents.length})</span></h2></div>{documents.length ? <div className="table-scroll"><table><thead><tr><th>Document</th><th>Type</th><th>Vendor</th><th>Date</th><th>Status</th></tr></thead><tbody>{documents.map(doc => <tr key={doc.id}><td><button className="document-link" onClick={() => openDoc(doc.id)}><FileText size={17} />{doc.filename}</button></td><td>{label(doc.type)}</td><td>{doc.vendorName}</td><td>{doc.createdAt.slice(0, 10)}</td><td><Pill status={doc.status} /></td></tr>)}</tbody></table></div> : <Empty text="No documents found. Try another filter or upload a file." />}</section>; }
function BillsTable({ bills, role, busy, decide, openDoc }: { bills: Bill[]; role: Role; busy: string; decide: (bill: Bill, decision: 'approve' | 'reject') => void; openDoc: (id: string) => void }) {
  const [filter, setFilter] = useState('all'); const filtered = bills.filter(b => filter === 'all' || b.status === filter);
  return <section className="panel"><div className="panel-heading"><h2>All bills</h2><select aria-label="Bill status" value={filter} onChange={e => setFilter(e.target.value)}>{['all', 'pending_approval', 'pending_review', 'scheduled', 'rejected'].map(s => <option key={s} value={s}>{label(s)}</option>)}</select></div><div className="table-scroll"><table><thead><tr><th>Vendor / rules</th><th>Amount</th><th>Due date</th><th>Status</th><th>Decision</th></tr></thead><tbody>{filtered.map(b => <tr key={b.id}><td><button className="document-link" disabled={!b.docId} onClick={() => b.docId && openDoc(b.docId)}>{b.vendor}</button><small className="table-sub">{b.glAccount}</small>{b.ruleHits.map(hit => <small className="rule-hit" key={hit}>{hit}</small>)}</td><td>{money(b.amount)}</td><td>{b.dueDate}</td><td><Pill status={b.status} /></td><td>{b.status === 'pending_approval' ? <div className="decision-buttons"><Button disabled={busy === b.id || !['owner', 'partner'].includes(role) || b.ruleHits.some(h => h.includes('missing'))} onClick={() => decide(b, 'approve')}><Check size={14} />Approve</Button><Button variant="outline" disabled={busy === b.id || !['owner', 'partner'].includes(role)} onClick={() => decide(b, 'reject')}>Reject</Button></div> : b.status === 'pending_review' ? <span className="muted">Review source fields with Ops</span> : <span className="muted">{b.status === 'scheduled' ? 'Mock payment' : 'Decision recorded'}</span>}</td></tr>)}</tbody></table></div>{!filtered.length && <Empty text="No bills with this status." />}</section>;
}
function Library({ documents, vendors, openDoc, exportPackage, exporting }: { documents: Document[]; vendors: Vendor[]; openDoc: (id: string) => void; exportPackage: () => void; exporting: boolean }) {
  const [query, setQuery] = useState(''); const [type, setType] = useState('all'); const [vendor, setVendor] = useState('all'); const [date, setDate] = useState('');
  const filtered = documents.filter(d => `${d.filename} ${d.vendorName}`.toLowerCase().includes(query.toLowerCase()) && (type === 'all' || d.type === type) && (vendor === 'all' || d.vendorName === vendor) && (!date || d.createdAt.slice(0, 10) >= date));
  return <><PageHeading eyebrow="DOCUMENT LIBRARY" title="Everything in its right place." description="Your documents and vendor relationships, easy to find." action={<Button disabled={exporting} onClick={exportPackage}><ArrowDownToLine size={16} />{exporting ? 'Preparing…' : 'Export package'}</Button>} /><div className="filters"><label className="search-field"><Search size={17} /><input aria-label="Search documents" placeholder="Search documents or vendors…" value={query} onChange={e => setQuery(e.target.value)} /></label><select aria-label="Document type" value={type} onChange={e => setType(e.target.value)}>{['all', 'invoice', 'receipt', 'payout_statement', 'w9', 'void_check'].map(t => <option key={t} value={t}>{t === 'all' ? 'All types' : label(t)}</option>)}</select><select aria-label="Vendor filter" value={vendor} onChange={e => setVendor(e.target.value)}><option value="all">All vendors</option>{Array.from(new Set(documents.map(d => d.vendorName))).map(v => <option key={v}>{v}</option>)}</select><input aria-label="Documents from date" type="date" value={date} onChange={e => setDate(e.target.value)} /></div><DocumentTable documents={filtered} openDoc={openDoc} /><section className="panel vendor-panel"><div className="panel-heading"><h2>Vendor memory</h2><span className="muted">Learned from your documents</span></div><div className="table-scroll"><table><thead><tr><th>Vendor</th><th>Default account</th><th>W-9</th><th>Void check</th><th>Bills</th></tr></thead><tbody>{vendors.map(v => <tr key={v.id}><td>{v.name}</td><td>{v.defaultGlAccount}</td><td>{v.hasW9 ? 'On file' : 'Missing'}</td><td>{v.hasVoidCheck ? 'On file' : 'Missing'}</td><td>{v.billCount}</td></tr>)}</tbody></table></div></section></>;
}
function Ask({ openDoc }: { openDoc: (id: string) => void }) {
  const [question, setQuestion] = useState(''); const [messages, setMessages] = useState<{ question: string; answer: Answer }[]>([]); const [pending, setPending] = useState(false); const [error, setError] = useState('');
  const send = async (q: string) => { if (!q.trim() || pending) return; setPending(true); setError(''); try { const answer = await api.ask(q.trim()); setMessages(m => [...m, { question: q.trim(), answer }]); setQuestion(''); } catch (e) { setError(message(e)); } finally { setPending(false); } };
  return <><PageHeading eyebrow="ASK YOUR BOOKS" title="Find the story in your numbers." description="Answers grounded in your practice's documents." /><section className="panel chat"><div className="chat-intro"><span className="insight-icon"><Sparkles size={24} /></span><h2>A little clarity, on demand.</h2><p>Ask about expenses, payouts or practice performance.</p><div className="chat-suggestions">{['Why did my margin drop in Q3?', 'Which payouts need follow-up?', 'What are my largest expenses?'].map(q => <button key={q} disabled={pending} onClick={() => void send(q)}>{q}<ArrowUpRight size={14} /></button>)}</div></div><div aria-live="polite">{messages.map((m, i) => <div className="chat-turn" key={i}><p className="question">{m.question}</p><div className="answer"><Sparkles size={17} /><div><p>{m.answer.answer}</p><small className="table-sub">Period: {m.answer.period}</small><div className="citations">{m.answer.citations.map(c => <button key={c.documentId} title={c.snippet} onClick={() => openDoc(c.documentId)}><FileText size={13} />{c.label}<ArrowUpRight size={12} /></button>)}</div></div></div></div>)}{pending && <p className="chat-pending"><LoaderCircle size={16} className="spin" />Looking through your books…</p>}{error && <p role="alert" className="text-red">{error}</p>}</div><form className="chat-input" onSubmit={e => { e.preventDefault(); void send(question); }}><input aria-label="Question about your books" value={question} onChange={e => setQuestion(e.target.value)} placeholder="Ask anything about your practice finances…" maxLength={2000} /><Button disabled={pending || !question.trim()} aria-label="Send question"><Send size={17} /></Button></form><small className="chat-disclaimer">{USE_MOCKS ? 'Demo answers use fixed sample context. ' : ''}Review cited sources. Answers support bookkeeping decisions.</small></section></>;
}
function Rules({ rules, notify, refresh }: { rules: Rule[]; notify: (text: string) => void; refresh: () => Promise<void> }) {
  const [show, setShow] = useState(false); const [busy, setBusy] = useState(false);
  return <><PageHeading eyebrow="APPROVAL RULES" title="Your practice. Your guardrails." description="Set the checks that keep your back office running smoothly." action={<Button onClick={() => setShow(!show)}><Plus size={16} />Create rule</Button>} />{show && <form className="panel rule-form" onSubmit={async e => { e.preventDefault(); const form = new FormData(e.currentTarget); setBusy(true); try { const field = String(form.get('field')); const raw = String(form.get('value')); await api.createRule({ name: String(form.get('name')), condition: { field, op: String(form.get('op')), value: field === 'amount' ? Number(raw) : raw === 'true' ? true : raw === 'false' ? false : raw }, action: String(form.get('action')) as Rule['action'], approverRole: String(form.get('role')) as Role }); setShow(false); await refresh(); notify('Rule created.'); } catch (err) { notify(message(err)); } finally { setBusy(false); } }}><h2>Create an approval rule</h2><label>Rule name<input name="name" required maxLength={100} placeholder="Require approval for large bills" /></label><div className="form-row"><label>Field<select name="field"><option value="amount">Bill amount</option><option value="vendor.hasW9">Vendor has W-9</option><option value="received">Received</option></select></label><label>Operator<select name="op"><option>&gt;</option><option>==</option><option>&lt;</option></select></label><label>Value<input name="value" required placeholder="1000 or false" /></label></div><div className="form-row"><label>Action<select name="action"><option value="require_approval">Require approval</option><option value="require_docs">Require documents</option><option value="block">Block payment</option></select></label><label>Approver<select name="role"><option value="partner">Partner</option><option value="owner">Owner</option><option value="ops">Operations</option></select></label></div><Button disabled={busy}>Save rule</Button>{USE_MOCKS && <small>Demo rules are stored for display. The sample approval flow uses predefined rules.</small>}</form>}<div className="rule-grid">{rules.map(r => <section className="panel rule-card" key={r.id}><ShieldCheck size={21} /><h2>{r.name}</h2><p><code>{r.condition.field} {r.condition.op} {String(r.condition.value)}</code></p><div><Pill status={r.action} /><span className="muted">{label(r.approverRole)}</span></div></section>)}</div></>;
}
function Transactions({ notify }: { notify: (text: string) => void }) { const [busy, setBusy] = useState(false); return <><PageHeading eyebrow="CARD TRANSACTIONS" title="Bring your spending into view." description="Import a CSV to categorize transactions and match receipts." /><section className="panel rule-form"><h2>Import transactions</h2><p>{USE_MOCKS ? 'CSV import is available when the backend endpoint is connected.' : 'Choose a CSV using the column format provided by your backend team.'}</p><input aria-label="Transaction CSV" type="file" accept=".csv,text/csv" disabled={busy || USE_MOCKS} onChange={async e => { const file = e.target.files?.[0]; if (!file) return; setBusy(true); try { const result = await api.importTransactions(file); notify(`${result.imported} imported · ${result.categorized} categorized · ${result.matchedReceipts} receipts matched`); } catch (err) { notify(message(err)); } finally { setBusy(false); } }} /></section></>; }
function DocumentRoute({ id }: { id: string }) { const [doc, setDoc] = useState<Document>(); const [vendors, setVendors] = useState<Vendor[]>([]); const [error, setError] = useState(''); useEffect(() => { let active = true; Promise.all([api.document(id), api.vendors()]).then(([d, v]) => { if (active) { setDoc(d); setVendors(v); } }).catch(e => { if (active) setError(message(e)); }); return () => { active = false; }; }, [id]); return error ? <div className="alert error">{error}</div> : doc ? <><PageHeading eyebrow="DOCUMENT DETAIL" title={doc.filename} description="Source document and extracted information, side by side." /><DocumentDetail doc={doc} vendors={vendors} /></> : <div className="skeleton" />; }
function DocumentDetail({ doc, vendors }: { doc: Document; vendors: Vendor[] }) { const recognized = vendors.find(v => v.name === doc.vendorName && v.billCount > 1); return <div className="document-detail"><div className="preview">{doc.viewUrl ? doc.viewUrl.startsWith('blob:') && /\.(png|jpe?g)$/i.test(doc.filename) ? <img src={doc.viewUrl} alt={doc.filename} /> : <iframe title={`Preview of ${doc.filename}`} src={doc.viewUrl} /> : <Empty text="Preview is not available yet." />}</div><section className="extracted"><div className="eyebrow">EXTRACTED INFORMATION</div><h2>{doc.vendorName || label(doc.type)}</h2><div className="document-badges"><Pill status={doc.status} /><span className={`pill ${doc.confidence >= .8 ? 'processed' : 'pending_review'}`}>{Math.round(doc.confidence * 100)}% confidence</span></div>{recognized && <div className="recognized"><Check size={15} />Recognized vendor · {recognized.billCount} prior bills</div>}{doc.confidence < .8 && <div className="alert">Low confidence. Operations should verify these fields before bill creation or approval.</div>}<dl>{Object.entries(doc.extracted ?? {}).map(([key, value]) => <div key={key}><dt>{label(key)}</dt><dd>{typeof value === 'object' ? JSON.stringify(value) : String(value)}</dd></div>)}</dl>{doc.viewUrl && <a className="document-link" href={doc.viewUrl} target="_blank" rel="noreferrer">Open original <ArrowUpRight size={14} /></a>}{USE_MOCKS && <small className="table-sub">Seed previews are fictional sample documents; uploaded previews show your file with simulated extracted fields.</small>}</section></div>; }
